### ISSUE TITLE
This repo is ORPHANED

### ISSUE THREAD

**Issue by djschaap** [pantheon-systems/rpmbuild-fusedav#3]
Filesystem squad does NOT own this repo; we do NOT have admin access to it; we are NOT using it for *anything*.

Whoever is still using this repo needs to claim ownership - else, this repo is on the path to being archived.

**Comment by joemiller** [comment]
Probably not in use anymore unless you're distributing fusedav via `.rpm`

**Comment by djschaap** [comment]
Hearing no objects, I'm archiving this repo.  So long, and thanks for all the fish.
